apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-svc 
  labels:
    app: ucoordinates-api
    tier: application
spec:
  type: NodePort 
  selector:
    app: coordinates-api
  ports:
  - port: 8000
    targetPort: 8000
    name: http
    protocol: TCP
    nodePort: 30080